services:
  app:
    build: .
    container_name: parser
    volumes:
      - .:/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: my_password
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: my_password
      ME_CONFIG_MONGODB_URL: "mongodb://admin:my_password@mongo:27017/"
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodata: null